spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-service?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application: 
   name: payment-service 
server:
  port: 8087